kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-system-fswriter-nodelabels-reader
  namespace: kube-system
subjects:
- kind: User
  name: system:serviceaccount:kube-system:nodelabels-fswriter
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: nodelabels-reader
  apiGroup: rbac.authorization.k8s.io
